version: "3.8"

services:
  api:
    build: .
    container_name: kfs_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: uvicorn kfs.main:app --host 0.0.0.0 --port 8000 --reload
